# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: 'Monitoring_Web/HealthMeasurement.Api/HealthMeasurement.Api.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ArtifactName: 'MonitoringHealthMeasurementAPI'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build $(ArtifactName)'
  name: BuildBackendProject
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Public $(ArtifactName)'
  name: PublishBackendProject
  inputs:
    command: 'publish'
    projects: '$(solution)'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(ArtifactName)'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(ArtifactName)'
    ArtifactName: $(ArtifactName)
    publishLocation: 'Container'