# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'Monitoring_Web/Monitoring_Web/Monitoring_Web.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ArtifactName: 'MonitoringWeb'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build $(ArtifactName)'
  name: BuildBackendProject
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Public $(ArtifactName)'
  name: PublishBackendProject
  inputs:
    command: 'publish'
    projects: '$(solution)'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(ArtifactName)'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(ArtifactName)'
    ArtifactName: $(ArtifactName)
    publishLocation: 'Container'