// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Notifications.DAL.EFModel
{
    public partial class SysNodeSetting
    {
        public int Id { get; set; }
        public string NodeName { get; set; }
        public int EnvironmentId { get; set; }
        public string MachineName { get; set; }
        public string Description { get; set; }
        public string ServiceList { get; set; }
        public string NotificationEmail { get; set; }
        public string ReportEmail { get; set; }
        public string NotificationAlias { get; set; }
        public string ReportAlias { get; set; }
        public DateTime? CreateDate { get; set; }
    }



}