// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Notifications.DAL.EFModel
{
    public partial class TransSystemHealth
    {
        public Guid Id { get; set; }
        public Guid? RequestId { get; set; }
        public int? EnvironmentId { get; set; }
        public string MachineName { get; set; }
        public byte? NotificationStatus { get; set; }
        public string Ipaddress { get; set; }
        public int? Cpuinfo { get; set; }
        public int? Cpuover { get; set; }
        public bool? CpuViolation { get; set; }
        public int? CpuViolationStatus { get; set; }
        public int? MemoryInfo { get; set; }
        public int? MemoryOver { get; set; }
        public bool? MemoryViolation { get; set; }
        public int? MemoryViolationStatus { get; set; }
        public int? StorageInfo { get; set; }
        public int? StorageOver { get; set; }
        public bool? StorageViolation { get; set; }
        public int? StorageViolationStatus { get; set; }
        public int? SystemViolationStatus { get; set; }
        public int? NumberOfTransactionFail { get; set; }
        public int? TransactionFailOver { get; set; }
        public DateTime? RequestTime { get; set; }
        public DateTime? ResponseTime { get; set; }
        public string ContentData { get; set; }
        public int? Status { get; set; }
        public string ErrorMessage { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}